### ISSUE TITLE
Compile error after upgrading prost to 0.12.1

### ISSUE THREAD

**Issue by Atry** [fdeantoni/prost-wkt#54]
```
error[E0277]: the trait bound `prost_wkt_types::Struct: prost::Message` is not satisfied
    --> router/client/src/pb/preemo_adapter_library.train.v1.rs:10:28
     |
10   | #[derive(Clone, PartialEq, ::prost::Message)]
     |                            ^^^^^^^^^^^^^^^^ the trait `prost::Message` is not implemented for `prost_wkt_types::Struct`
     |
     = help: the following other types implement trait `prost::Message`:
               ()
               Annotation
               Api
               Box<M>
               CachedBatch
               ClearCacheRequest
               ClearCacheResponse
               CodeGeneratorRequest
             and 97 others
note: required by a bound in `message::merge`
```

**Comment by tiagolobocastro** [comment]
Seems the cargo toml was updated, but not "released" yet
Gentle reminder @fdeantoni in case you simply forgot to "release" (I'm not familiar with the workflow here)

**Comment by fdeantoni** [comment]
I have not forgotten, simply giving some more time to test things out. Prost 0.12 introduces some new things and I want to be sure nothing is broken. If all goes well I expect to release 0.5.0 by the end of this week.

**Comment by fdeantoni** [comment]
Version 0.5.0 has been released!
